
# This file tells Netlify how to handle SPA routing
[build]
  publish = "dist"
  command = "npm run build"

# The following redirect rule tells Netlify that when a request comes in to any path,
# it should serve the index.html file and let the client-side router handle the path
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add headers to allow Stripe webhooks
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization, stripe-signature"
