// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqkzmcudulutohnskcwt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhxa3ptY3VkdWx1dG9obnNrY3d0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwOTYzNDYsImV4cCI6MjA1NDY3MjM0Nn0.tAKrMlKJHP0K8pQq9JOOBLiatgFTKRGf8__fCovFCZA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);